language: node_js
node_js: "10"

install: npm install

script: npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master